version: "3"

networks:
    dbwebb:

services:
    server:
        container_name: "server"
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports: 
            - "1337:1337"
        networks:
            dbwebb:
        volumes:
            - ./backend:/server
            - /server/node_modules/

    adminwebb:
        container_name: "adminwebb"
        build:
            context: ./frontend/adminwebb
            dockerfile: Dockerfile
        ports: 
            - "1338:3000"
        networks:
            dbwebb:
        volumes:
            - ./frontend/adminwebb:/frontend/adminwebb
            - /frontend/adminwebb/node_modules/
        environment:
            - WATCHPACK_POLLING=true

    customermobile:
        container_name: "customermobile"
        build:
            context: ./frontend/customermobile
            dockerfile: Dockerfile
        ports: 
            - "1339:3000"
        networks:
            dbwebb:
        volumes:
            - ./frontend/customermobile:/frontend/customermobile
            - /frontend/customermobile/node_modules/
        environment:
            - WATCHPACK_POLLING=true

    customerwebb:
        container_name: "customerwebb"
        build:
            context: ./frontend/customerwebb
            dockerfile: Dockerfile
        ports: 
            - "1340:3000"
        networks:
            dbwebb:
        volumes:
            - ./frontend/customerwebb:/frontend/customerwebb
            - /frontend/customerwebb/node_modules/
        environment:
            - WATCHPACK_POLLING=true

    database:
        image: "mysql:latest"
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        volumes:
            - db_vol:/var/lib/mysql
            - ./db/:/docker-entrypoint-initdb.d/
        ports:
            - "3308:3306"
        networks:
            dbwebb:
        environment:
            MYSQL_ROOT_PASSWORD: pass
        
volumes:
    db_vol: